package com.example.kleenpride.data.booking

import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.QuerySnapshot
import com.google.android.gms.tasks.Task
import com.google.android.gms.tasks.Tasks

/**
 * Data class that represents a single booking entry.
 * Default values are added so Firestore can deserialize objects easily
 */

data class Booking(
    val title: String = "",
    val date: String = "",
    val price: String = "",
    val status: String = "",
    val id: String = ""
)

/**
 * Repository responsible for interacting with Firebase Firestore
 * Handles data operations (create, fetch, etc.) related to bookings
 */

class BookingRepository {

    // Firestore instance for database access
    private val firestore = FirebaseFirestore.getInstance()

    // Firebase Authentication instance to get the logged-in user
    private val auth = FirebaseAuth.getInstance()

    /**
     * Fetch all bookings that belong to the currently logged-in user.
     * Returns a Firestore snapshot asynchronously
     */
    fun getUserBookings(): Task<QuerySnapshot> {
        // Get current user ID or fail if not logged in
        val uid = auth.currentUser?.uid ?: return Tasks.forException(Exception("User not authenticated"))

        // Navigate to: users/{uid}/bookings collection and fetch all documents
        return firestore.collection("users")
            .document(uid)
            .collection("bookings")
            .get()
    }

    /**
     * Create a new booking document inside the user's Firestore collection
     * Each booking will have a unique ID generated by Firestore
     */
    fun createBooking(booking: Booking): Task<Void> {
        val uid = auth.currentUser?.uid ?: return Tasks.forException(Exception("User not authenticated"))

        // Create a new document reference with an auto-generated ID
        val bookingRef = firestore.collection("users")
            .document(uid)
            .collection("bookings")
            .document()

        // Write the booking data to Firestore
        return bookingRef.set(booking.copy(id = bookingRef.id))
    }
}